# SwiftLint Configuration

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - function_parameter_count
  - nesting

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_first_last

included:
  - Sources/EasyLoggingSDK

excluded:
  - .build
  - Carthage
  - Pods
  - Tests

type_body_length:
  warning: 250
  error: 350

file_length:
  warning: 500
  error: 800

reporter: "xcode"

custom_rules:
  redundant_nil_coalescing:
    included: ".*.swift"
    name: "Redundant nil coalescing"
    regex: "\\?\\? nil"
    message: "Redundant nil coalescing found"
    severity: warning
